In [1]:
import pandas as pd
#loading final output
df = pd.read_csv("/Users/prabinrimal/Desktop/New>>>>>/text extraction/resumes_extracted.csv")
df

,resume_id,resume_text,category,file_path
0,0,Hieu-Thi Luong\ncontact@hieuthi.com | https://...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1,1,bitbucket.org/mikkujacob | github.com/mikhailj...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
2,2,"MERT KIRAY\nGörresstr. 3, 80798 München\n+4915...",AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
3,3,Adam Pardyl Email : adam@pardyl.com\nPhD Candi...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
4,4,Karystinaios\nEmmanouil AI Researcher — Music ...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
...,...,...,...,...
1598,1598,NaN,Testing and QA,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1599,1599,NaN,Testing and QA,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1600,1600,NaN,Testing and QA,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1601,1601,NaN,Testing and QA,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1602,1602,NaN,Testing and QA,/Users/prabinrimal/Desktop/New>>>>>/Collected ...

In [2]:
# drop duplicate rows
df = df.drop_duplicates()

# drop rows with missing or empty resume_text
df = df.dropna(subset=['resume_text'])
df = df[df['resume_text'].astype(str).str.strip() != '']

# drop rows where resume_text (after stripping) is shorter than 50 characters
df = df[df['resume_text'].astype(str).str.strip().str.len() >= 50]

# reset index and show result
df = df.reset_index(drop=True)
df

,resume_id,resume_text,category,file_path
0,0,Hieu-Thi Luong\ncontact@hieuthi.com | https://...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1,1,bitbucket.org/mikkujacob | github.com/mikhailj...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
2,2,"MERT KIRAY\nGörresstr. 3, 80798 München\n+4915...",AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
3,3,Adam Pardyl Email : adam@pardyl.com\nPhD Candi...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
4,4,Karystinaios\nEmmanouil AI Researcher — Music ...,AI ML,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
...,...,...,...,...
1424,1530,"Aidan M. Levinson\n5271 Wheatland Drive, Zions...",Technology Consultant,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1425,1531,Arturo Hernandez Jr.\nEducation\nCORNELL COLLE...,Technology Consultant,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1426,1532,Jide Akanni\njide.akanni361@gmail.com\nCell (2...,Technology Consultant,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1427,1533,Kurt Mansperger 845-797-0506  @kurtmansperger...,Technology Consultant,/Users/prabinrimal/Desktop/New>>>>>/Collected ...
1428,1534,Shelly Falconer\nvirtualshelly@gmail.com (585)...,Technology Consultant,/Users/prabinrimal/Desktop/New>>>>>/Collected ...

In [3]:
df = df[["resume_id", "resume_text", "category"]]
df.to_csv("final_dataset.csv", index=False)
df

,resume_id,resume_text,category
0,0,Hieu-Thi Luong\ncontact@hieuthi.com | https://...,AI ML
1,1,bitbucket.org/mikkujacob | github.com/mikhailj...,AI ML
2,2,"MERT KIRAY\nGörresstr. 3, 80798 München\n+4915...",AI ML
3,3,Adam Pardyl Email : adam@pardyl.com\nPhD Candi...,AI ML
4,4,Karystinaios\nEmmanouil AI Researcher — Music ...,AI ML
...,...,...,...
1424,1530,"Aidan M. Levinson\n5271 Wheatland Drive, Zions...",Technology Consultant
1425,1531,Arturo Hernandez Jr.\nEducation\nCORNELL COLLE...,Technology Consultant
1426,1532,Jide Akanni\njide.akanni361@gmail.com\nCell (2...,Technology Consultant
1427,1533,Kurt Mansperger 845-797-0506  @kurtmansperger...,Technology Consultant
1428,1534,Shelly Falconer\nvirtualshelly@gmail.com (585)...,Technology Consultant